Vagrant.configure("2") do |config|
  config.vm.define "web", primary: true do |web|
  web.vm.box = "sbeliakou/centos-6.7-x86_64"
  web.vm.hostname = "web"
  web.vm.network "private_network", ip: "192.168.100.10"
  web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provider "virtualbox" do |host|
	host.name="web-frontend"
	host.cpus = 1
	host.memory = 512

	end
  web.vm.provision "shell", inline: "echo WebServer"
  web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "app" do |app|
  app.vm.box = "sbeliakou/centos-6.7-x86_64"
  app.vm.hostname = "app"
  app.vm.network "private_network", ip: "192.168.100.11"
  app.vm.network "forwarded_port", guest: 80, host: 8081
  app.vm.provider "virtualbox" do |host|
        host.name="app-backend"
	host.customize ["modifyvm", :id, "--cpuexecutioncap", "35"]
        host.memory = 1024
        end
  app.vm.provision "shell", inline: "echo AppServer"
  app.vm.provision "shell", path: "app.sh"
   end
config.vm.provision "shell", inline: <<-SHELL
echo "This host is ready for provisioning" 
yum install -y vim
SHELL
config.vm.synced_folder "sources/", "/home/vagrant/sources",
owner: "vagrant", group: "vagrant",
create: true

end
